// <auto-generated />
using System;
using Dzeta.TonWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dzeta.TonWatcher.Migrations
{
    [DbContext(typeof(TonWatcherDbContext))]
    [Migration("20250613172818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dzeta.TonWatcher.Infrastructure.Entities.Transaction", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("AccountAddress")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("account_address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Lt")
                        .HasColumnType("bigint")
                        .HasColumnName("lt");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TransactionDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("transaction_data");

                    b.Property<long>("Utime")
                        .HasColumnType("bigint")
                        .HasColumnName("utime");

                    b.Property<bool>("WebhookNotified")
                        .HasColumnType("boolean")
                        .HasColumnName("webhook_notified");

                    b.Property<DateTime?>("WebhookNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("webhook_notified_at");

                    b.HasKey("Hash");

                    b.HasIndex("Lt");

                    b.HasIndex("WebhookNotified");

                    b.ToTable("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
